"""create_attendance_table

Revision ID: e0fa8aee8b1b
Revises: 19866e18364c
Create Date: 2026-06-15 13:51:40.684075+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# ---------------------------------------------------------------------------
# Revision identifiers — used by Alembic
# ---------------------------------------------------------------------------
revision: str = 'e0fa8aee8b1b'
down_revision: Union[str, Sequence[str], None] = '19866e18364c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('employee_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the associated employee'),
    sa.Column('attendance_date', sa.Date(), nullable=False, comment='The date of this attendance record'),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the employee checked in'),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the employee checked out'),
    sa.Column('total_hours', sa.Numeric(precision=5, scale=2), nullable=False, comment='Total hours worked for the day'),
    sa.Column('attendance_status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'LATE', name='attendancestatus', native_enum=False, length=20), nullable=False, comment='Status for the day (e.g., Present, Absent, Half-Day, Late)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_attendance_date'), 'attendances', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendances_employee_id'), 'attendances', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendances_employee_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_attendance_date'), table_name='attendances')
    op.drop_table('attendances')
    # ### end Alembic commands ###
