"""create_leave_tables

Revision ID: d0a539fe0864
Revises: e0fa8aee8b1b
Create Date: 2026-06-15 14:10:19.703691+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# ---------------------------------------------------------------------------
# Revision identifiers — used by Alembic
# ---------------------------------------------------------------------------
revision: str = 'd0a539fe0864'
down_revision: Union[str, Sequence[str], None] = 'e0fa8aee8b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_balances',
    sa.Column('employee_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the associated employee'),
    sa.Column('leave_type', sa.Enum('CASUAL', 'SICK', 'EARNED', 'UNPAID', name='leavetype', native_enum=False, length=20), nullable=False, comment='The type of leave this balance entry tracks'),
    sa.Column('year', sa.Integer(), nullable=False, comment='The calendar year this balance applies to'),
    sa.Column('allocated_days', sa.Integer(), nullable=False, comment='Total days allocated for this leave type in the given year'),
    sa.Column('used_days', sa.Integer(), nullable=False, comment='Total days consumed by approved leave requests'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_balances_employee_id'), 'leave_balances', ['employee_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('employee_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the associated employee'),
    sa.Column('leave_type', sa.Enum('CASUAL', 'SICK', 'EARNED', 'UNPAID', name='leavetype', native_enum=False, length=20), nullable=False, comment='Type of leave requested (e.g. Casual, Sick, Earned, Unpaid)'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Start date of the leave period'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='End date of the leave period'),
    sa.Column('total_days', sa.Integer(), nullable=False, comment='Total number of calendar days in the leave request'),
    sa.Column('reason', sa.String(length=255), nullable=False, comment='Reason provided for the leave application'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus', native_enum=False, length=20), nullable=False, comment='Current validation status of the request'),
    sa.Column('approved_by', sa.Uuid(), nullable=True, comment='Foreign key referencing the user/admin who approved/rejected the request'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of when the request status was processed'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_approved_by'), 'leave_requests', ['approved_by'], unique=False)
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_start_date'), 'leave_requests', ['start_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_start_date'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_approved_by'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_leave_balances_employee_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    # ### end Alembic commands ###
